import createClient from "openapi-fetch";
import type { paths } from "./bindings"; // generated by openapi-typescript

export type { components } from "./bindings";
export const client = createClient<paths>();
